events/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

from events.views import IndexView, MainPanelView, CrearEvento, EventDetail, EventEdit, DeleteEvent

urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^panel/$', MainPanelView.as_view(), name="panel"),
    url(r'^panel/evento/nuevo/$', CrearEvento.as_view(), name="nuevo"),
    url(r'^panel/evento/(?P<pk>\d+)/$', EventDetail.as_view(), name="detalle"),
    url(r'^panel/evento/editar/(?P<pk>\d+)/$', EventEdit.as_view(), name="editar"),
    url(r'^panel/evento/eliminar/(?P<pk>\d+)/$', DeleteEvent.as_view(), name="eliminar")
]

eventus/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('users.urls', namespace="users_app")),
    url(r'^', include('events.urls', namespace="events_app")),
]

users/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login/$', 'users.views.UserLogin', name="login"),
    url(r'^salir/$', 'users.views.UserLogOut', name="logout"),
)

events/models.py
from django.db import models
from django.contrib import admin 
from django.template.defaultfilters import slugify

from django.conf import settings

# Create your models here.

class TimeStampModel(models.Model):
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now_add=True)

	class Meta:
		abstract = True 

class Category(models.Model):
	name=models.CharField(max_length=50)
	slug=models.SlugField(editable=False)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name)
			super(Category, self).save(*args, **kwargs)

	def __unicode__(self):
		return self.name

class Event(TimeStampModel):
	name=models.CharField(max_length=200, unique=True)
	slug=models.SlugField(editable=False)
	summary=models.TextField(max_length=255)
	content=models.TextField()
	category=models.ForeignKey(Category)
	place=models.CharField(max_length=50)
	start=models.DateTimeField()
	finish=models.DateTimeField()
	image=models.ImageField(upload_to='events') 
	is_free = models.BooleanField(default=True)
	amount=models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
	views = models.PositiveIntegerField(default=0)
	organizer=models.ForeignKey(settings.AUTH_USER_MODEL) 

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name)
		super(Event, self).save(*args, **kwargs)

	def __unicode__(self):
		return self.name

class Assistant(TimeStampModel):
	assistant=models.ForeignKey(settings.AUTH_USER_MODEL)
	event=models.ManyToManyField(Event)
	attended=models.BooleanField(default=False)
	has_paid=models.BooleanField(default=False)

	def __unicode__(self):
		return "%s %s" % (self.assistant.username, self.event.name)


class Comment(TimeStampModel):
	user=models.ForeignKey(settings.AUTH_USER_MODEL)
	event=models.ForeignKey(Event)
	content=models.TextField()

	def __unicode__(self):
		return "%s %s" % (self.user.username, self.event.name)

admin.site.register(Comment)
admin.site.register(Category)

events/forms.py
from django import forms
from .models import Event

class EventoForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ('views', 'organizer', 'created', 'modified',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'summary': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'place': forms.TextInput(attrs={'class': 'form-control'}),
            'start': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'finish': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'is_free': forms.CheckboxInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
        }

events/views.py
from django.http import request
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView
from .models import Event, Category, Comment
from .forms import EventoForm
from users.models import User
from django.core.urlresolvers import reverse, reverse_lazy


# Create your views here.


# def index(request):
#     events = Event.objects.all().order_by('-created')[:6]
#     categories = Category.objects.all()
#     print events
#     print categories
#     return render(request,  'events/index.html', {'events': events,
#                                         'categories': categories})

class IndexView(TemplateView):
    template_name = 'events/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['events'] = Event.objects.all().order_by('-created')[:6]
        context['categories'] = Category.objects.all()
        return context


# def main_panel(request):
#     events = Event.objects.filter(organizer__username='manuh').order_by('is_free', '-created')
#     cantidad_eventos = events.count()
#     return render(request, 'events/panel/panel.html', {'events': events, 'cantidad': cantidad_eventos })


class MainPanelView(TemplateView):
    template_name = 'events/panel/panel.html'

    def get_context_data(self, **kwargs):
        context = super(MainPanelView, self).get_context_data(**kwargs)
        context['events'] = Event.objects.filter(organizer = self.request.user).order_by('is_free', '-created')
        context['cantidad'] = context['events'].count()
        return context


# def crear_evento(request):
#     if request.method == 'POST':
#         modelform = EventoForm(request.POST, request.FILES)
#         if modelform.is_valid():
#             u = User.objects.get(pk=1)
#             nuevo_evento = modelform.save()
#             nuevo_evento.organizer = u
#             nuevo_evento.save()
#             return redirect(reverse('events_app:panel'))
#     else:
#         modelform = EventoForm()
#
#     return render(request, 'events/panel/crear_evento.html', {'form': modelform})

class CrearEvento(CreateView):
    form_class = EventoForm
    template_name = 'events/panel/crear_evento.html'
    success_url = reverse_lazy('events_app:panel')

    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super(CrearEvento, self).form_valid(form)


# def detalle_evento(request, evento_id):
#     event = get_object_or_404(Event, pk=evento_id)
#     return render(request, 'events/panel/detalle_evento.html', {'event': event})

class EventDetail(DetailView):
    template_name = 'events/panel/detalle_evento.html'
    model = Event


# def editar_evento(request, evento_id):
#     event = get_object_or_404(Event, pk=evento_id)
#
#     if request.method == 'POST':
#         modelform = EventoForm(request.POST, request.FILES, instance=event)
#         if modelform.is_valid():
#             modelform.save()
#             return redirect(reverse('events_app:panel'))
#     else:
#         modelform = EventoForm(instance=event)
#
#     return render(request, 'events/panel/editar_evento.html', {'form': modelform, 'event': event})

class EventEdit(UpdateView):
    template_name = 'events/panel/editar_evento.html'
    model = Event
    form_class = EventoForm
    success_url = reverse_lazy('events_app:panel')
    
    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super(EventEdit, self).form_valid(form)


# def eliminar_evento(request, evento_id):
#     event = get_object_or_404(Event, pk=evento_id)
#
#     if request.method == 'POST':
#         event.delete()
#         return redirect(reverse('events_app:panel'))
#
#     return render(request, 'events/panel/eliminar_evento.html', {'event': event})

class DeleteEvent(DeleteView):
    template_name = 'events/panel/eliminar_evento.html'
    model = Event
    success_url = reverse_lazy('events_app:panel')
    context_object_name = 'event'

templates/events/panel/crear_evento.html
{% extends "events/base_events.html" %}

{% block title %}
    Panel
{% endblock title %}

{% block content %}

    {% include "events/panel/navbar.html" %}

    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'events_app:panel'%}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left">Regresar</span>
                </a>
                <strong>Crear Evento</strong>
            </h4>
        </div> <!-- Page Header -->

        <div class="row">
            <div class="col-md-12">
                <form role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span>
                    Ingresa los datos de tu evento y compartelo con todos tus conocidos.</p>

                    {% if forms.error %}
                        <div class="alert alert-dismissible alert-danger" role="alert">
                            {{ form.error }}
                         </div>
                    {% endif %}

                    <div class="form-group">
                        <label for="">{{ form.name.label_tag }}</label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.summary.label_tag }}</label>
                        {{ form.summary }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.content.label_tag }}</label>
                        {{ form.content }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.category.label_tag }}</label>
                        {{ form.category }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.place.label_tag }}</label>
                        {{ form.place }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.start.label_tag }}</label>
                        {{ form.start }}
                        <p class="help-block">El evento iniciará. DD/MM/AA HH/MM/SS</p>
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.finish.label_tag }}</label>
                        {{ form.finish }}
                        <p class="help-block">El evento terminará. DD/MM/AA HH/MM/SS</p>
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.image.label_tag }}</label>
                        {{ form.image }}
                    </div>
                    <div class="checkbox">
                        <label for=""> {{ form.is_free.label_tag }}</label>
                        {{ form.is_free }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.amount.label_Tag }}</label>
                        {{ form.amount }}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save event</button>
                    </div>

                </form>
            </div>
        </div>
    </div>

{% endblock content %}

templates/events/panel/detalle_evento.html
{% extends 'events/base_events.html' %}

{% block title %} Panel {% endblock title %}

{% block content %}

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target=".navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="iconbar"></span>
                    <span class="iconbar"></span>
                    <span class="iconbar"></span>
                </button>
                <a class="navbar-brand" href="#">Eventus</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav pull-right">
                    <li><a href="">Sign Up</a></li>
                    <li><a href="">Login</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'events_app:panel' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Evento: {{ event.name }}</strong>
            </h4>
        </div>

        <div class="row">

            <div class="col-md-3 text-center">
                <img src="{{ event.image}}" alt="{{ event.name }}" class="img-rounded">
            </div>

            <div class="col-md-9">

                <table class="table">
                    <tbody>
                        <tr>
                            <th>Name</th>
                            <td>{{ event.name }}</td>
                        </tr>
                        <tr>
                            <th>Category</th>
                            <td>{{ event.category }}</td>
                        </tr>
                        <tr>
                            <th>Content</th>
                            <td>{{ event.content }}</td>
                        </tr>
                        <tr>
                            <th>Start / Finish</th>
                            <td>{{ event.start }} / {{ event.finish }}</td>
                        </tr>
                        <tr>
                            <th>Place</th>
                            <td>{{ event.place }}</td>
                        </tr>
                        <tr>
                            <th>Amount</th>
                            <td>
                                {% if event.is_free %}
                                    <span class="label label-default">Gratuito</span>
                                {% else %}
                                    <span class="label label-info">S/. {{ event.amount }}</span>
                                {% endif %}

                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>



{% endblock content %}

templates/events/panel/editar_evento.html
{% extends 'events/base_events.html' %}

{% block title %} Editar {% endblock title %}

{% block content %}

    {% include "events/panel/navbar.html" %}

    <div class="container">

    <div class="page-header">
            <h4>
                <a href="{% url 'events_app:panel' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Editando: {{ event.name }}</strong>
            </h4>
    </div>

    <div class="row">
            <div class="col-md-12">
                <form role="form" action="{% url 'events_app:editar' event.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span>
                    Ingresa los datos de tu evento y compartelo con todos tus conocidos.</p>

                    {% if forms.error %}
                        <div class="alert alert-dismissible alert-danger" role="alert">
                            {{ form.error }}
                         </div>
                    {% endif %}

                    <div class="form-group">
                        <label for="">{{ form.name.label_tag }}</label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.summary.label_tag }}</label>
                        {{ form.summary }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.content.label_tag }}</label>
                        {{ form.content }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.category.label_tag }}</label>
                        {{ form.category }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.place.label_tag }}</label>
                        {{ form.place }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.start.label_tag }}</label>
                        {{ form.start }}
                        <p class="help-block">El evento iniciará. DD/MM/AA HH/MM/SS</p>
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.finish.label_tag }}</label>
                        {{ form.finish }}
                        <p class="help-block">El evento terminará. DD/MM/AA HH/MM/SS</p>
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.image.label_tag }}</label>
                        {{ form.image }}
                    </div>
                    <div class="checkbox">
                        <label for=""> {{ form.is_free.label_tag }}</label>
                        {{ form.is_free }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.amount.label_Tag }}</label>
                        {{ form.amount }}
                    </div>
                    <div class="form-group">
                        <label for="">{{ form.organizer.label_Tag }}</label>
                        {{ form.organizer }}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save event</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/events/panel/eliminar_evento.html
{% extends 'events/base_events.html' %}

{% block title %} Eliminar {% endblock title %}

{% block content %}

    {% include "events/panel/navbar.html" %}

    <div class="container">

    <div class="page-header">
            <h4>
                <a href="{% url 'events_app:panel' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Eliminando: {{ event.name }}</strong>
            </h4>
    </div>

        <div class="col-md-12">

            <form action="{% url 'events_app:eliminar' event.id %}" role="form" method="POST">
                {% csrf_token %}
                <p class="">¿Desea eliminar el evento "{{ event.name }}"?</p>
                <input type="submit" class="btn btn-danger">
                <a href="{% url 'events_app:panel' %}" class="btn btn-default">No</a>
            </form>

        </div>

    </div>



{% endblock content %}

templates/events/panel/navbar.html
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target=".navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="iconbar"></span>
                    <span class="iconbar"></span>
                    <span class="iconbar"></span>
                </button>
                <a class="navbar-brand" href="/">Eventus</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav pull-right">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'events_app:panel' %}">Hola, {{ user.username }}</a></li>
                        <li><a href="{% url 'users_app:logout' %}">Log out</a></li>
                    {% else %}
                        <li><a href="{% url 'users_app:login' %}">Sign Up</a></li>
                        <li><a href="{% url 'users_app:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
</div>

templates/events/panel/panel.html
{% extends "events/base_events.html" %}

{% block title %}
    Panel de Control
{% endblock title %}

{% block content %}

    {% include "events/panel/navbar.html" %}

    <div class="container">
        <div class="page-header">
            <h4>
                <strong>
                    Tienes <span class="label label-warning">{{ cantidad }}</span> Eventos disponibles
                </strong>
                <a href="{% url 'events_app:nuevo' %}" class="btn btn-primary pull-right">
                    <span class="glyphicon glyphicon-plus">Crear nuevo evento</span>
                </a>
            </h4>
        </div> <!-- Termina header -->

    <div class="row">
    <div class="col-md-12">
        <table class="table table-stripped table-hover">
            <thead>
            <tr>
                <th colspan="2">Nombre del evento</th>
                <th>Categoría</th>
                <th>Inicio</th>
                <th>Fin</th>
                <th>Monto</th>
                <th class="text-center">Acciones</th>
            </tr>
            </thead>
            <tbody>
                {% for event in events %}

                    <tr>
                    <td>
                        <img src="{{ event.imagen.url }}" alt="{{ event.name }}" width="60" class="img-rounded">
                    </td>
                    <td>{{ event.name }}</td>
                    <td>{{ event.category }}</td>
                    <td>{{ event.start }}</td>
                    <td>{{ event.finish }}</td>
                    <td>
                        {% if event.is_free %}
                            <span class="label label-default">Gratuito</span>
                        {%  else %}
                             <span class="label label-info">S/. {{ event.amount }}</span>
                        {% endif %}
                    </td>
                    <td class="text-right">
                        <a href="{% url 'events_app:detalle' event.id %}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                        <a href="{% url 'events_app:editar' event.id %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="{% url 'events_app:eliminar' event.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                    </td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
    </div>
{% endblock content %}